config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  root 'roots#top'
  get '/admin_top', to: 'roots#admin_top'
  get '/maps', to: 'roots#map'

  get '/posts/hashtag/:name', to: 'posts#hashtag'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers, :users_posts
      get :liked_posts
    end
  end
  resources :relationships, only: [:create, :destroy]



  resources :posts do
    member do
      get :liked_users
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.create(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    @post.reload
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>

    <% unless post.like_user(current_user.id).blank? %>
        <div class="vertical_like">
            <%= link_to post_like_path(post_id: post.id, id: post.likes[0].id), method: :delete, remote: true do %>
                    <i class="fas fa-heart"></i>
            <% end %>
            <% if post.liked_users.size > 0 %>
                <%= link_to liked_users_post_path(post) do %>
                    <%= post.liked_users.size %>likes
                <% end %>
            <% end %>
        </div>
    <% else %>
        <div class="vertical_like">
            <%= link_to post_likes_path(post.id), method: :post, remote: true do %>
                <i class="far fa-heart"></i>
            <% end %>
            <% if post.liked_users.size > 0 %>
                <%= link_to liked_users_post_path(post) do %>
                    <%= post.liked_users.size %>likes
                <% end %>
            <% end %>
        </div>
    <% end %>

<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");