config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  root 'roots#top'
  get '/admin_top', to: 'roots#admin_top'
  get '/maps', to: 'roots#map'

  get '/posts/hashtag/:name', to: 'posts#hashtag'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers, :users_posts
      get :liked_posts
    end
  end
  resources :relationships, only: [:create, :destroy]



  resources :posts do
    member do
      get :liked_users
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :user_name,uniqueness: true, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy


  # いいね機能
  has_many :likes, dependent: :destroy
  # いいねした投稿
  has_many :liked_posts, through: :likes, source: :post

  # フォロー機能
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end
  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end
  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end


  has_one_attached :avatar
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin, only:[:index]


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:captures_attachments).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def liked_posts
    @user = User.find(params[:id])
    @posts = @user.liked_posts.includes(:captures_attachments)
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :password, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
    end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
    <%= f.hidden_field :following_id %>
    <%= f.submit "Follow", class: "btn btn-sm btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
        <%  if current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <% else %>
            <%= render 'follow' %>
        <% end %>
    </div>
<% end %>

app/views/users/_stats.html.erb
<div class="container">
    <div class="row">
        <% @user ||= current_user %>
        <div class="stats">
            <%= link_to following_user_path(@user) do %>
                <strong id="following" class="stat">
                    <%= @user.followings.count %>
                </strong>follow
            <% end %>
            |
            <%= link_to followers_user_path(@user) do %>
                <strong id="followers" class="stat">
                    <%= @user.followers.count %>
                </strong>follower
            <% end %>
        </div>
    </div>
</div>


<!-- 
<div class="modal_wrap">
    <input id="trigger2" type="checkbox">
    <div class="modal_overlay">
        <label for="trigger2" class="modal_trigger"></label>
        <div class="modal_content">
            <label for="trigger2" class="close_button">✖️</label>
            <p><strong>フォロー中</strong></p>
            <div class="fuser text-center">
                <% @user.followings.find_each do |user| %>
                    <%= link_to user_path(user) do %>
                        <% if user.avatar.attached? %>
                            <%= image_tag user.avatar.variant(combine_options:{resize:"50x50^",crop:"50x50+0+0", gravity: :center}).processed, class: "user-avatar"  %>
                        <% else %>
                            <%= image_tag 'img/no_image_user.png', :size => '50x50', class: "user-avatar" %>
                        <% end %>
                    <% end %>
                    <%= link_to user_path(user) do %>
                        <%= user.user_name %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="modal_wrap">
    <input id="trigger3" type="checkbox">
    <div class="modal_overlay">
        <label for="trigger3" class="modal_trigger"></label>
        <div class="modal_content">
            <label for="trigger3" class="close_button">✖️</label>
            <p><strong>フォロワー</strong></p>
            <div class="fusers text-center">
                <% @user.followers.each do |user| %>
                    <div class="fuser">
                        <%= link_to user_path(user) do %>
                            <% if user.avatar.attached? %>
                                <%= image_tag user.avatar.variant(combine_options:{resize:"50x50^",crop:"50x50+0+0"}, gravity: :center).processed, class: "user-avatar" %>
                            <% else %>
                                <%= image_tag 'img/no_image_user.png', :size => '50x50', class: "user-avatar" %>
                            <% end %>
                        <% end %>
                        <%= link_to user_path(user) do %>
                            <%= user.user_name %>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div> -->

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-sm follow-btn btn-default" %>
<% end %>

app/views/users/edit.html.erb
    <body id="body">
        <div class="container">
            <div class="row">
                <h2 class="text-center">ユーザー情報編集</h2>
                <%= form_with model: @user, local: true do |f| %>
                    <h4 class="text-center">ユーザー</h4>
                    <div class="field text-center">
						<span> <i class="far fa-user"></i> </span>
						<%= f.text_field :user_name %>
                    </div>
                    <div class="text-center">
                        <span><i class="far fa-user-circle"> <%= f.file_field :avatar, class: "field" %></i></span>
                    </div>
                    <div class="text-center">
                        <%= f.submit '更新', class: "btn btn-primary" %>
                        <%= link_to 'back', user_path(@user), class: "btn btn-default" %>
                    </div>
                <% end %>
            </div>
        </div>
    </body>

app/views/users/liked_posts.html.slim
body#body
    .container
        .row
            .liked-posts.text-center
                h3.text-center Liked Posts
                - @user.liked_posts.includes(:user).find_each do |post|
                    = link_to post_path(post) do
                        - post.captures.find_each do |capture|
                            = image_tag capture.variant(combine_options:{resize: '300x300^', crop: '300x300+0+0', gravity: :center}).processed

app/views/users/show.html.erb
<body id="body">
        <% if user_signed_in? %>
            <div class="suser-box">
                <div class="avatar">
                    <% if @user.avatar.attached? %>
                        <%= image_tag @user.avatar, :size => "200x200", class: "user-avatar" %>
                    <% else %>
                        <%= image_tag '/images/img/no_image_user.png', :size => "200x200", class: "user-avatar" %>
                    <% end %>
                </div>
                <div class="suser-info">
                    <div class="user-name">
                        <strong><%= @user.user_name %></strong>
                        <div class="user-edit">
                            <% if @user == current_user %>
                                <%= link_to "Edit Profile", edit_user_path(current_user), class: 'btn btn-sm btn-default' %>
                            <% end %>
                        </div>
                        <div class="follow_form"><%= render 'follow_form', class: "follow_form" %></div>
                    </div>
                    <div>
                        <strong><%= @user.posts.size %></strong> Posts
                    </div>
                    <div class="follow">
                        <div class="stats"><%= render 'stats' %></div>
                    </div>
                    <strong><%= link_to 'Liked Posts', liked_posts_user_path(@user) %></strong>
                </div>
            </div>
            <div class="text-center">
                <% if @user.posts.size == 0 %>
                    <h4>No Posts Yet</h4>
                    <strong><%= link_to 'Create New Post', new_post_path, class: 'btn btn-default' %></strong>
                <% elsif @user.posts.size > 0 %>
                    <h4><%= @user.user_name %>'s Posts</h4>
                <% end %>
            </div>
            <div class="text-center">
                <% @posts.each do |post| %>
                    <% post.captures.each do |capture| %>
                        <%= link_to post_path(post.id) do %>
                            <%= image_tag capture.variant(combine_options:{resize:"300x300^",crop:"300x300+0+0",gravity: :center}).processed, class: "users-capture" %>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        <% end %>
</body>

app/views/users/show_follow.html.slim
body#body
    .container
        .row
            i.fas.fa-user-friends
                = link_to ' Follower List', followers_user_path(@user)
            h3 Follow List
            table.table.table-default
                thred.thred-default
                    tr
                        th 
                            i.far.fa-user-circle
                        th Name
                        th Posts
                        th
                tbody
                    - @user.followings.find_each do |user|
                        tr
                            td= link_to user_path(user) do
                                - if user.avatar.attached?
                                    = image_tag user.avatar.variant(combine_options:{resize:'50x50^',crop:'50x50+0+0',gravity: :center}).processed, class: 'user-avatar'
                                - else
                                    = image_tag '/images/img/no_image_user.png', :size => '50x50', class: 'user-avatar'
                            td= user.user_name
                            td
                                strong= user.posts.size
                                |posts
                            td
                                i.far.fa-hand-point-right
                                    = link_to ' detail', user_path(user)

app/views/users/show_follower.html.slim
body#body
    .container
        .row
            i.fas.fa-user-friends
                = link_to ' Follow List', following_user_path(@user)
            h3 Follower List
            table.table.table-default
                thred.thred-default
                    tr
                        th
                            i.far.fa-user-circle
                        th Name
                        th Posts
                        th
                tbody
                    - @user.followers.find_each do |user|
                        tr
                            td= link_to user_path(user) do
                                - if user.avatar.attached?
                                    = image_tag user.avatar.variant(combine_options:{resize:"50x50^", crop: "50x50+0+0", gravity: :center}).processed, class: "user-avatar"
                                - else
                                    = image_tag 'images/img/no_image_user.png', :size => '50x50', class: 'user-avatar'
                            td= user.user_name
                            td
                                strong= user.posts.size 
                                |posts
                            td
                                i.far.fa-hand-point-right
                                    = link_to ' detail', user_path(user)