config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  root 'roots#top'
  get '/admin_top', to: 'roots#admin_top'
  get '/maps', to: 'roots#map'

  get '/posts/hashtag/:name', to: 'posts#hashtag'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers, :users_posts
      get :liked_posts
    end
  end
  resources :relationships, only: [:create, :destroy]



  resources :posts do
    member do
      get :liked_users
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :nation
    has_many :comments, dependent: :destroy

    # いいね
    has_many :likes, dependent: :destroy
    # いいねしたユーザー
    has_many :liked_users, through: :likes, source: :user
    def like_user(user_id)
        likes.find_by(user_id: user_id)
    end



    # tag
    has_and_belongs_to_many :tags
    after_create do
        post = Post.find_by(id: self.id)
        hashtags = self.caption.scan(/[#＃][Ａ-Ｚａ-ｚA-Za-z一-鿆0-9０-９ぁ-ヶｦ-ﾟー]+/)
        hashtags.uniq.map do |hashtag|
            tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#＃'))
            post.tags << tag
        end
    end
    before_update do
        post = Post.find_by(id: self.id)
        post.tags.clear
        hashtags = self.caption.scan(/[#＃][Ａ-Ｚａ-ｚA-Za-z一-鿆0-9０-９ぁ-ヶｦ-ﾟー]+/)
        hashtags.uniq.map do |hashtag|
            tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#＃'))
            post.tags << tag
        end
    end

    has_many_attached :captures
    validates :captures, presence: true

    validates :caption, length: { maximum: 400 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only:[:new, :create, :show, :edit, :update, :hashtag]
    before_action :authenticate_correct_user, only:[:edit, :update]

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if params[:create_button]
            if @post.save
                redirect_to posts_path
            else
                render :new
            end
        else
            if @post.save
                render :success
            else
                render :error
            end
        end
    end

    def index
        if user_signed_in?
            @user = current_user
            @userf = @user.followings.with_attached_avatar.page(params[:page]).per(16).reverse_order
        end
        @q = Post.with_attached_captures.includes(:captures_attachments, :user, :nation, :likes).ransack(params[:q])
        @result = @q.result(distinct: true).page(params[:page]).per(16).reverse_order
        @like = Like.new
        @post = Post.new
    end

    def show
        @like = Like.new
        @post = Post.find(params[:id])
        @comment = Comment.new
        @comments = @post.comments.reverse_order
        @latestposts = @post.user.posts.last(3)
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post_update
            redirect_to posts_path
        else
            render 'edit'
        end
    end

    def hashtag
        if user_signed_in?
            @user = current_user
            @userf = @user.followings.page(params[:page]).per(16).reverse_order
        end
        tag = Tag.find_by(name: params[:name])
        @posts = tag.posts.page(params[:page]).per(16).reverse_order
        @like = Like.new
        @post = Post.new
    end

    def destroy
        @post = Post.find(params[:id])
        if @post.destroy
            redirect_to user_path(current_user.id)
        end
    end

    def liked_users
        @post = Post.find(params[:id])
        @user = @post.liked_users.find_by(params[:user_id])
    end

    private
    def post_params
        params.require(:post).permit(:user_id, :nation_id, :naiton_name, :caption, captures: [])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
    def render_with_hashtag(caption)
        caption.gsub(/[#＃][Ａ-Ｚａ-ｚA-Za-z一-鿆0-9０-９ぁ-ヶｦ-ﾟー]+/){ |word| link_to word, "/posts/hashtag/#{word.delete("#＃")}" }.html_safe
    end
    def extraction_hashtag(caption)
        caption.scan(/[#＃][Ａ-Ｚａ-ｚA-Za-z一-鿆0-9０-９ぁ-ヶｦ-ﾟー]+/).map(&:strip)
    end
end

app/views/posts/_user_info.html.erb
<div>
    <div id="user-info">
        <div class="user-info clearfix">
            <div class="user-info">
                <%= link_to user_path(user) do %>
                    <%= user.user_name %>
                <% end %>
            </div>
            <div class="user-info">
                <%= link_to user_path(user) do %>
                    <% if user.avatar.attached? %>
                        <%= image_tag user.avatar.variant(combine_options:{resize:"120x120^",crop:"120x120+0+0",gravity: :center}).processed, class: "user-avatar" %>
                    <% else %>
                        <%= image_tag "/images/img/no_image_user.png", :size => "120x120", class: "user-avatar" %>
                    <% end %>
                <% end %>
            </div>
            <div class="user-info">
                <%= render 'users/stats' %>
            </div>
            <div class="liked_button user-info">
                <strong><%= link_to 'Liked Posts', liked_posts_user_path(@user) %></strong>
            </div>
            <div class="user-info">
                <label class="postn_button">New Post</label>
            </div>
            <div id="tab-menu" class="user-info">
                <div class="tab-headline">
                    <a href="#tab1" class="active">
                        <i class="far fa-images"></i>
                        <span><strong>All Posts</strong></span>
                    </a>
                </div>
                <div class="tab-headline">
                    <a href="#tab2" class="">
                        <i class="far fa-clock"></i>
                        <span><strong>Timeline</strong></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- liked posts -->

app/views/posts/edit.html.erb
<body id="bodypostn">
        <div class="container">
            <div class="row">
                <div class="">
                    <h2>new Post</h2>
                    <%= form_with model: @post do |f| %>
                    <div class="error-message"></div>
                        <div class="field">
                            <%= f.label :capture %>
                            <% @post.captures.each do |capture| %>
                                <%= image_tag capture.variant(combine_options:{resize:"614x614^",crop:"614x614+0+0",gravity: :center}).processed %>
                            <% end %>
                        </div>
                        <div class="field">
                            <%= f.label :caption %>
                            <%= f.text_area :caption, class: "form-control", placeholder: "コメントを入力" %>
                        </div>
                        <div class="field">
                            <%= f.label :nation %>
                            <%= f.select :nation_id, options_from_collection_for_select(Nation.all, :id, :nation_name, @post.nation_id), {}, class: "searchable" %>
                        </div>
                        <div>
                            <%= f.submit "create", class: "btn" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
</body>

app/views/posts/error.js.erb
$('.error-message').text("<%= @post.errors.full_messages.join(",").html_safe %>");

app/views/posts/hashtag.html.erb
<body id="body">
    <div class="container">
        <div class="row">
            <div class="clearfix col-xs-offset-1">
                <div class="nav sidebar-nav affix user-info-box" role="complementary">
                    <% if user_signed_in? %>
                        <%= render 'posts/user_info', user: current_user, post: @post %>
                    <% end %>
                </div>
            </div>
            <div class="posts-box col-xs-offset-2">
                <div id="tab-contents">
                    <div id="tab1" class="tab">
                        <div id="posts" class="posts">
                            <% @posts.each do |post| %>
                                <div class="post">
                                    <div class="post-user-info">
                                        <div>
                                            <%= link_to user_path(post.user) do %>
                                                <% if post.user.avatar.attached? %>
                                                    <%= image_tag post.user.avatar.variant(combine_options:{resize:"50x50^",crop:"50x50+0+0",gravity: :center}).processed, class: "user-avatar" %>
                                                <% else %>
                                                    <%= image_tag "/images/img/no_image_user.png", :size => "50x50", class: "user-avatar" %>
                                                <% end %>
                                            <% end %>
                                            <%= link_to user_path(post.user) do %>
                                                <%= post.user.user_name %>
                                            <% end %>
                                        </div>
                                        <div class="createddate">
                                            投稿日時｜<%= post.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                                        </div>
                                    </div>
                                    <div class="post-capture-box">
                                        <%= link_to post_path(post) do %>
                                            <% post.captures.find_each do |capture| %>
                                                <%= image_tag capture.variant(combine_options:{resize:"614x614^",crop:"614x614+0+0",gravity: :center}).processed, class: "post-capture" %>
                                            <% end %>
                                        <% end %>
                                    </div>
                                    <div class="post-info">
                                        <div class="nation-name">
                                            Country : <%= truncate(post.nation.nation_name, :length => 34, :omission => "...") %>
                                        </div>
                                        <div id="likes_buttons_<%= post.id %>" class="likes_button">
                                            <%= render partial: 'likes/like', locals: { post: post, likes: @likes } %>
                                        </div>
                                        <div>
                                            <% if post.caption.length > 80 %>
                                                <div class="grad-wrap">
                                                    <input id="trigger_<%= post.id %>" class="grad-trigger" type="checkbox">
                                                    <label class="grad-btn" for="trigger_<%= post.id %>">view full text</label>
                                                    <div class="grad-item">
                                                        <%= render_with_hashtag(post.caption) %>
                                                    </div>
                                                </div>
                                            <% else %>
                                                <%= render_with_hashtag(post.caption) %>
                                            <% end %>
                                        </div>
                                    </div>
                                    <nav class="pagination"><%= paginate @posts %></nav>
                                </div>
                            <% end %>
                        </div>
                    </div>
                    <div id="tab2" class="tab">
                        <% if user_signed_in? %>
                            <% @userf.find_each do |user| %>
                            <% @posts = Post.where(user_id: user.id).reverse_order %>
                                <% @posts.each do |post| %>
                                    <div class="post">
                                        <div class="post-user-info">
                                            <div>
                                                <%= link_to user_path(post.user) do %>
                                                    <% if post.user.avatar.attached? %>
                                                        <%= image_tag post.user.avatar.variant(combine_options:{resize:"50x50^",crop:"50x50+0+0",gravity: :center}).processed, class: "user-avatar" %>
                                                    <% else %>
                                                        <%= image_tag "/images/img/mo_image_user.png", :size => "50x50", class: "user-avatar" %>
                                                    <% end %>
                                                <% end %>
                                                <%= link_to user_path(post.user) do %>
                                                    <%= post.user.user_name %>
                                                <% end %>
                                            </div>
                                            <div class="createddate">
                                                Posting Date｜<%= post.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
                                            </div>
                                        </div>
                                        <div class="post-capture-box">
                                            <%= link_to post_path(post) do %>
                                                <% post.captures.find_each do |capture| %>
                                                    <%= image_tag capture.variant(combine_options:{resize:"614x614^",crop:"614x614+0+0",gravity: :center}).processed, class: "post-capture" %>
                                                <% end %>
                                            <% end %>
                                        </div>
                                        <div class="post-info">
                                            <div class="nation-name">
                                                    Country : <%= truncate(post.nation.nation_name, :length => 40, :omission => "...") %>
                                            </div>
                                            <div id="likes_buttons_<%= post.id %>" class="likes_button">
                                                <%= render partial: 'likes/like', locals: { post: post, likes: @likes } %>
                                            </div>
                                            <div>
                                                <% if post.caption.length > 80 %>
                                                    <div class="grad-wrap">
                                                        <input id="trigger_<%= post.id %>" class="grad-trigger" type="checkbox">
                                                        <label class="grad-btn" for="trigger_<%= post.id %>">view full text</label>
                                                        <div class="grad-item">
                                                            <%= render_with_hashtag(post.caption) %>
                                                        </div>
                                                    </div>
                                                <% else %>
                                                    <%= render_with_hashtag(post.caption) %>
                                                <% end %>
                                            </div>
                                        </div>
                                    </div>
                                <% end %>
                            <% end %>
                            <nav class="pagination"><%= paginate @userf %></nav>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <span id="back" class="backicon">
            <a href="#">
                <i class="fas fa-chevron-up fa-lg"></i>
            </a>
        </span>
    </div>
</body>



     <!-- new- post-modal -->
     <div class="postn_modal_wrapper">
            <div class="postn_modal">
                <div class="postn_modal_content">
                    <h2>New Post</h2>
                    <%= form_with model: @post do |f| %>
                    <div class="error-message"></div>
                        <div class="field">
                            <%= f.label :capture %>
                            <%= f.file_field :captures, multiple: true %>
                            <!-- <div class="preview"></div> -->
                        </div>
                        <div class="field">
                            <%= f.label :caption %>
                            <%= f.text_area :caption, class: "form-control", placeholder: "コメントを入力" %>
                        </div>
                        <div class="field">
                            <%= f.label :nation %>
                            <%= f.select :nation_id, options_from_collection_for_select(Nation.all, :id, :nation_name, @post.nation_id), {}, class: "searchable" %>
                        </div>
                        <div>
                            <%= f.submit "create", class: "btn" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>

app/views/posts/liked_users.html.slim
body#body
    .container
        .row
            h3.text-center Liked Users
            table.table.table-default
                thred.thred-default
                    tr
                        th
                        th Name
                        th Posts
                        th
                tbody
                    - @post.liked_users.find_each do |user|
                        tr
                            td= link_to user_path(user) do
                                - if user.avatar.attached?
                                    = image_tag user.avatar.variant(combine_options:{resize: '50x50^', crop: '50x50+0+0', gravity: :center}).processed, class: 'user-avatar'
                                - else
                                    = image_tag '/images/img/no_image_user.png', :size => '50x50', class: 'user-avatar'
                            td= user.user_name
                            td
                                strong= user.posts.size
                                |posts
                            td
                                i.far.fa-hand-point-right
                                    = link_to ' detail', user_path(user)

app/views/posts/new.html.erb
<body id="body">
    <div class="container">
            <h2 class="text-center">Create new Post</h2>
            <%= form_with model: @post do |f| %>
                <div class="post-new">
                    <div class="field">
                        <span><i class="fa fa-camera"></i> <strong>Captutre</strong></span>
                        <%= f.file_field :captures, multiple: true %>
                        <div class="preview">
                            <%= image_tag '/images/img/no_image.jpg', :size => "614x614", class: "preview" %>
                        </div>
                    </div>
                    <div class="post-new">
                        <div class="field">
                            <span><i class="far fa-comment"></i> <strong>Caption</strong></span><br/>
                            <%= f.text_area :caption, class: "form-control", placeholder: "Enter comment" %>
                        </div>
                        <div class="field">
                            <span><i class="fas fa-globe-americas"></i> <strong>Country</strong></span><br/>
                            <%= f.select :nation_id, options_from_collection_for_select(Nation.all, :id, :nation_name, @post.nation_id), {}, class: "searchable" %>
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <%= f.submit "create", class: "btn btn-default btn-lg", name: "create_button" %>
                </div>
            <% end %>
    </div>
</body>

app/views/posts/show.html.erb
<body id="body">
    <div class="container col-xs-offset-2">
        <% if user_signed_in? %>
            <div class="row post-show">
                <div  class="post-showb">
                    <div class="scapture">
                        <% if @post.captures.attached? %>
                            <% @post.captures.each do |capture| %>
                                <%= image_tag capture.variant(combine_options:{resize:"614x614^",crop:"614x614+0+0",gravity: :center}).processed %>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="spost-info">
                        <div class="nation">
                            <i class="fas fa-globe-americas"></i> <%= @post.nation.nation_name %>
                        </div>
                        <div class="caption">
                            <%= render_with_hashtag(@post.caption) %>
                        </div>
                        <div class="fav" id="likes_buttons_<%= @post.id %>">
                            <%= render partial: 'likes/like', locals: { post: @post, likes: @likes } %>
                        </div>
                    </div>
                    <div class="createddate">
                        Posting Date｜<%= @post.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                    </div>
                    <div>
                        <% if user_signed_in? %>
                            <% if current_user.id == @post.user_id or current_user.admin? %>
                                Post |
                                <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-sm btn-primary' %>
                                :
                                <%= link_to 'Delete', post_path, method: :delete, "data-confirm" => "Are you sure？", class: 'btn btn-sm btn-default' %>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="spost-user-box">
                        <div class="spost-user-info">
                            <h4 class="">Poster：
                                <%= link_to user_path(@post.user_id) do %>
                                    <%= @post.user.user_name %>
                                <% end %>
                            </h4>
                            <div>
                                <%= link_to user_path(@post.user_id) do %>
                                    <% if @post.user.avatar.attached? %>
                                        <%= image_tag @post.user.avatar.variant(combine_options:{resize:"150x150^",crop:"150x150+0+0",gravity: :center}).processed, class: "user-avatar" %>
                                    <% else %>
                                        <%= image_tag '/images/img/no_image_user.png', :size => "150x150", class: "user-avatar" %>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                        <div class="latestposts-box">
                            <h4>Latest Posts by <%= @post.user.user_name %>：</h4>
                            <div>
                                <% @latestposts.each do |post| %>
                                    <% post.captures.find_each do |capture| %>
                                        <%= link_to post_path(post.id) do %>
                                            <%= image_tag capture.variant(combine_options:{resize:"100x100^",crop:"100x100+0+0",gravity: :center}).processed, class: "latestposts" %>
                                        <% end %>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="comments">
                    <div class="comments-new">
                        <% if user_signed_in? %>
                            <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
                        <% end %>
                        <h4><strong> Comments</strong></h4>
                        <div id="comments_area">
                            <%= render partial: 'comments/index', locals: { comments: @comments } %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</body>


<div class="modal_wrap">
        <input id="triggery" type="checkbox">
        <div class="modal_overlay">
            <label for="triggery" class="modal_trigger"></label>
            <div class="modal_content">
                <label for="triggery" class="close_button">✖️</label>
                <p><strong>いいねしたユーザー</strong></p>
                <div class="fusers">
                    <% @post.liked_users.each do |user|%>
                        <div class="fuser">
                            <%= link_to user_path(user) do %>
                                <% if user.avatar.attached? %>
                                    <%= image_tag user.avatar, :size => "50x50", class: "user-avatar" %>
                                <% else %>
                                    <%= image_tag 'img/no_image_user.png', :size => "50x50", class: "user-avatar" %>
                                <% end %>
                            <% end %>
                            <%= link_to user_path(user) do %>
                                <%= user.user_name %>
                            <% end %>
                        </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/posts/success.js.erb
$('input[type="text"]').val('');
$('.postn_modal_wrapper, .postn_modal, .postn_modal_content').hide(function(){
    window.location.reload();
});