config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  root 'roots#top'
  get '/admin_top', to: 'roots#admin_top'
  get '/maps', to: 'roots#map'

  get '/posts/hashtag/:name', to: 'posts#hashtag'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers, :users_posts
      get :liked_posts
    end
  end
  resources :relationships, only: [:create, :destroy]



  resources :posts do
    member do
      get :liked_users
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>tirpfrom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/css/swiper.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&amp;subset=japanese" rel="stylesheet">
  </head>

  <body>
    <header class="navbar navbar-fixed-top">
      <div class="container">
        <nav class="col-xs-offset-9">
          <% if user_signed_in? %>
           <% user_name = current_user.user_name %>
          <% else %>
            <% user_name = "guest" %>
          <% end %>
          Welcome<strong><%= " #{user_name}" %></strong>！
        </nav>
      </div>

      <div class="container navs">
        <nav class="nav navbar-nav navbar-left">
          <%= link_to root_path do %>
            <%= image_tag "img/logo.jpg", size:"50x50", id: "logo" %>
          <% end %>
          |
          <strong id="tripfrom">
            <%= link_to root_path do %>trip from<% end %>
          </strong>
          |
          <%= link_to "go everywhere", maps_path , id: "catchphrase" %>
          <dl class="searchbox">
              <% provide(:post_caption, 'All posts') %>
              <%= search_form_for @q do |f| %>
                  <dt><%= f.text_field :user_user_name_or_caption_or_nation_nation_name_cont ,placeholder: ' Search Posts...' %></dt>
                  <dd>
                      <%= button_tag( class: "search-btn") do %>
                          <%= content_tag :span, "", class: "fa fa-search" %>
                      <% end %>
                  </dd>
              <% end %>
          </dl>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "admintop", admin_top_path %></li>
              <li><%= link_to "users", users_path %></li>
              <li><%= link_to "posts", posts_path %></li>
              <li><%= link_to "log_out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li>
                <div class="header-item">
                  <%=link_to posts_path do %>
                    <span class="header-icon"><i class="far fa-images"></i></span>
                    <p> Posts</p>
                  <% end %>
                </div>
              </li>
              <li>
                <div class="header-item">
                  <%=link_to user_path(current_user.id) do %>
                    <span class="header-icon"><i class="fa fa-user"></i></span>
                    <p> MyPage</p>
                  <% end %>
                </div>
              </li>
              <li>
                <div class="header-item">
                  <%= link_to new_post_path do %>
                    <span class="header-icon"><i class="fas fa-camera"></i></span>
                    <p> NewPost</p>
                  <% end %>
                </div>
              </li>
              <li>
                <div class="header-item">
                  <%=link_to maps_path do %>
                    <span class="header-icon"><i class="fas fa-map-marker-alt"></i></span>
                    <p> Trip</p>
                  <% end %>
                </div>
              </li>
              <li>
                <div class="header-item">
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <span class="header-icon"><i class="fas fa-sign-out-alt"></i></span>
                    <p> LogOut</p>
                  <% end %>
                </div>
              </li>
            <% end %>
          <% else %>
            <li>
              <div class="header-item">
                <%=link_to posts_path do %>
                  <span class="header-icon"><i class="far fa-images"></i></span>
                  <p> Posts</p>
                <% end %>
              </div>
            </li>
            <li>
              <div class="header-item sign_button sign_up_button">
                <span class="header-icon"><i class="fas fa-user-plus"></i></span>
                <p> SignUp</p>
              </div>
            </li>
            <li>
              <div class="header-item sign_button sign_in_button">
                <span class="header-icon"><i class="fas fa-sign-in-alt"></i></span>
                <p> LogIn</p>
              </div>
            </li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <!-- modal signup login -->
        <div class="sign_modal_wrapper">
          <div class="sign_modal">
            <div class="sign_up_modal sign_modal_content">
              <h2 class="new-users-headline">Sign Up</h2>
              <form class="new_user"action="/users" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="tWQXIbdNUc+zFnHvDa/A7ASlxc5CQn+eaaE/oGQDWU/5y0I77MiFigp6WQX9tjn0GUmHNViBO3rIFNYllj6WYw==">
                <div class="field">
                    <span> <i class="fa fa-user"></i> </span>
                    <input autofocus="autofocus" autocomplete="user_name" type="user_name" type="user_name" name="user[user_name]" placeholder=" Nick name" >
                </div>

                <div class="field">
                    <span> <i class="fa fa-envelope"></i> </span>
                    <input autofocus="autofocus" autocomplete="email" type="email" value="" name="user[email]" placeholder=" Email adress">
                </div>

                <div class="field">
                    <span> <i class="fa fa-lock"></i> </span>
                    <input autocomplete="new-password" type="password" name="user[password]" aria-autocomplete="list" placeholder=" 6 characters minimum">
                </div>

                <div class="field">
                    <span> <i class="fa fa-lock"></i> </span>
                    <input autocomplete="new-password" type="password" name="user[password_confirmation]" placeholder=" Repeat password">
                </div>

                <div class="actions">
                  <input type="submit" name="commit" value="Sign up" data-disable-with="Sign up">
                </div>
              </form>
            </div>
            <div class="sign_in_modal sign_modal_content">
              <h2>Log In</h2>
              <form class="new_user" action="/users/sign_in" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="ATN3VBw0hRBi8JwLEs8fCBiic/7VxLGZZGDVI6RSVr55wgNTl50canQaDHgEpozHn9rCEl27Lz0Z4VJMVTJKpw==">
                <div class="field">
                  <label for="user_user_name">User Name</label><br>
                  <input autofocus="autofocus" autocomplete="user_name" type="user_name" type="user_name" name="user[user_name]" >
                </div>

                <div class="field">
                  <label for="user_password">Password</label><br>
                  <input autocomplete="current-password" type="password" name="user[password]">
                </div>

                <div class="field">
                  <input name="user[remember_me]" type="hidden" value="0"><input type="checkbox" value="1" name="user[remember_me]">
                  <label for="user_remember_me">Remember me</label>
                </div>

                <div class="actions ">
                  <input type="submit" name="commit" value="Log in" data-disable-with="Log in">
                </div>
              </form>
            </div>
          </div>
        </div>


    <%= yield %>

    <footer class="footer">
      <div class="col-xs-offset-9">tripfrom</div>
    </footer>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/js/swiper.min.js"></script>
      <script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.min.js"></script>
  </body>
</html>